[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["Mock721", "Mock1155", "MockHarvestContract", "MockAuctionsContract", "HarvestTest", "AuctionsTest"]
via_ir = true
evm_version = 'cancun'

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
1 = { key = "${ETHERSCAN_API_KEY}" }
11155111 = { key = "${ETHERSCAN_API_KEY}" }
8453 = { key = "${BASESCAN_API_KEY}" }
84532 = { key = "${BASESCAN_API_KEY}" }
137 = { key = "${POLYGONSCAN_API_KEY}" }
80002 = { key = "${POLYGONSCAN_API_KEY}" }